image:
  repository: image-registry.openshift-image-registry.svc:5000/c72cba-tools/met-cron
  pullPolicy: Always
  namespace: c72cba-tools
  tag: "test"

replicaCount: 1

resources:
  cpu:
    limit: 100m
    request: 100m
  memory:
    limit: 512Mi
    request: 100Mi

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

configMapData:
  EMAIL_ENVIRONMENT: You are using a Test environment
  ENGAGEMENT_CLOSEOUT_EMAIL_TEMPLATE_ID: b7ea041b-fc30-4ad3-acb2-82119dd4f95d
  ENGAGEMENT_CLOSING_SOON_EMAIL_TEMPLATE_ID: 30344886-ea33-4ca2-83e1-e5ebe9c3457d
  IS_SINGLE_TENANT_ENVIRONMENT: 'true'
  NOTIFICATIONS_EMAIL_ENDPOINT: 'https://epic-engage-notify-api-test.apps.gold.devops.gov.bc.ca/api/v1/notifications/email'
  OFFSET_DAYS: '2'
  PUBLISH_ENGAGEMENT_EMAIL_TEMPLATE_ID: 7bf2ffcd-d69e-4c3f-9aa0-e8e89b491e92
  SITE_URL: 'https://test.engage.eao.gov.bc.ca'