apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      initContainers:
      - name: pre-hook
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/opt/app-root/pre-hook-update-db.sh"]
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: met-database-users
              key: analytics-username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: met-database-users
              key: analytics-password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: met-patroni
              key: app-db-name
        - name: DATABASE_HOST
          value: met-patroni16
        - name: CORS_ORIGIN
          value: {{ .Values.corsOrigin }}
        - name: DATABASE_PORT
          value: '5432'
        resources:
          limits:
            cpu: {{ .Values.resources.cpu.limit }}
            memory: {{ .Values.resources.memory.limit }}
          requests:
            cpu: {{ .Values.resources.cpu.request }}
            memory: {{ .Values.resources.memory.request }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          limits:
            cpu: {{ .Values.resources.cpu.limit }}
            memory: {{ .Values.resources.memory.limit }}
          requests:
            cpu: {{ .Values.resources.cpu.request }}
            memory: {{ .Values.resources.memory.request }}
        # readinessProbe:
        #   httpGet:
        #     path: /api/readyz
        #     port: 8080
        #     scheme: HTTP
        #   timeoutSeconds: 10
        #   periodSeconds: 10
        #   successThreshold: 1
        #   failureThreshold: 3
        # livenessProbe:
        #   httpGet:
        #     path: /api/healthz
        #     port: 8080
        #     scheme: HTTP
        #   timeoutSeconds: 10
        #   periodSeconds: 10
        #   successThreshold: 1
        #   failureThreshold: 3
        env:
            - name: FLASK_ENV
              value: production
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: met-database-users
                  key: analytics-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: met-database-users
                  key: analytics-password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: met-patroni
                  key: app-db-name
            - name: DATABASE_HOST
              value: met-patroni16
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3
                  key: secret-access-key
            - name: CORS_ORIGIN
              value: {{ .Values.corsOrigin }}
        envFrom:
            - configMapRef:
                name: jwt-oidc
        ports:
          - containerPort: 8080
            protocol: TCP
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler