kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Chart.Name }}
data:
  IS_SINGLE_TENANT_ENVIRONMENT: "{{ .Values.configMapData.IS_SINGLE_TENANT_ENVIRONMENT }}"
  KEYCLOAK_CLIENT_ID: {{ .Values.configMapData.KEYCLOAK_CLIENT_ID }}
  KEYCLOAK_URL: {{ .Values.configMapData.KEYCLOAK_URL }}
  PENGUIN_ANALYTICS_URL: {{ .Values.configMapData.PENGUIN_ANALYTICS_URL }}
  EAO_VERIFICATION_EMAIL_TEMPLATE_ID: {{ .Values.configMapData.EAO_VERIFICATION_EMAIL_TEMPLATE_ID }}
  ACCESS_REQUEST_EMAIL_ADDRESS: {{ .Values.configMapData.ACCESS_REQUEST_EMAIL_ADDRESS }}
  SUBSCRIBE_EMAIL_TEMPLATE_ID: {{ .Values.configMapData.SUBSCRIBE_EMAIL_TEMPLATE_ID }}
  ANALYTICS_ENABLED: "{{ .Values.configMapData.ANALYTICS_ENABLED }}"
  CLOSED_ENGAGEMENT_REJECTED_EMAIL_TEMPLATE_ID: {{ .Values.configMapData.CLOSED_ENGAGEMENT_REJECTED_EMAIL_TEMPLATE_ID }}
  PENGUIN_ANALYTICS_SOURCE_APP: {{ .Values.configMapData.PENGUIN_ANALYTICS_SOURCE_APP }}
  EAO_ENGAGEMENT_CLOSEOUT: {{ .Values.configMapData.EAO_ENGAGEMENT_CLOSEOUT }}
  KEYCLOAK_REALMNAME: {{ .Values.configMapData.KEYCLOAK_REALMNAME }}
  KEYCLOAK_BASE_URL: {{ .Values.configMapData.KEYCLOAK_BASE_URL }}
  NOTIFICATIONS_EMAIL_ENDPOINT: {{ .Values.configMapData.NOTIFICATIONS_EMAIL_ENDPOINT }}
  EMAIL_ENVIRONMENT: {{ .Values.configMapData.EMAIL_ENVIRONMENT }}
  ACCESS_REQUEST_EMAIL_TEMPLATE_ID: {{ .Values.configMapData.ACCESS_REQUEST_EMAIL_TEMPLATE_ID }}
  IS_EAO_ENVIRONMENT: "{{ .Values.configMapData.IS_EAO_ENVIRONMENT }}"
  SUBMISSION_RESPONSE_EMAIL_TEMPLATE_ID: {{ .Values.configMapData.SUBMISSION_RESPONSE_EMAIL_TEMPLATE_ID }}
  EMAIL_SECRET_KEY: {{ .Values.configMapData.EMAIL_SECRET_KEY }}
  PENGUIN_ANALYTICS_ENABLED: "{{ .Values.configMapData.PENGUIN_ANALYTICS_ENABLED }}"
  SITE_URL: {{ .Values.configMapData.SITE_URL }}
  VERIFICATION_EMAIL_TEMPLATE_ID: {{ .Values.configMapData.VERIFICATION_EMAIL_TEMPLATE_ID }}
  EAO_SUBMISSION_REPORT: {{ .Values.configMapData.EAO_SUBMISSION_REPORT }}
  REJECTED_EMAIL_TEMPLATE_ID: {{ .Values.configMapData.REJECTED_EMAIL_TEMPLATE_ID }}